### ISSUE TITLE
flickity is not a function TypeError

### ISSUE THREAD

**Issue by CultofRobots** [CultofRobots/ratingsbyrobots#9]
This needs to be fixed or replaced. 
Possible fix here: https://github.com/metafizzy/flickity/issues/543#issuecomment-295306100

Chromium Console log:
```
jquery.min.js:2 jQuery.Deferred exception: $(...).flickity is not a function TypeError: $(...).flickity is not a function
    at HTMLDocument.<anonymous> (https://rbr.cultofrobots.net/js/custom.js:45:37)
    at l (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:29375)
    at c (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: $(...).flickity is not a function
    at HTMLDocument.<anonymous> (custom.js:45)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)

```

**Comment by CultofRobots** [comment]
Removing flickity altogether for something I don't hate.
